name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get ctsnews.m3u8
      run: |
        touch ./ctsnews.m3u8
        sudo cat >./ctsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=UkeLZMHNJpA)
        EOL
    - name: Get ctitv.m3u8
      run: |
        touch ./ctitv.m3u8
        sudo cat >./ctitv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=_QbRXRnHMVY)
        EOL
    - name: Get ttvnews.m3u8
      run: |
        touch ./ttvnews.m3u8
        sudo cat >./ttvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get ftvnews.m3u8
      run: |
        touch ./ftvnews.m3u8
        sudo cat >./ftvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/FTVLIVE/live)
        EOL
    - name: Get ctvnews.m3u8
      run: |
        touch ./ctvnews.m3u8
        sudo cat >./ctvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/twctvnews/live)
        EOL
    - name: Get setlive.m3u8
      run: |
        touch ./setlive.m3u8
        sudo cat >./setlive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/三立LIVE新聞/live)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/setmoney159/live)
        EOL
    - name: Get ebcnews.m3u8
      run: |
        touch ./ebcnews.m3u8
        sudo cat >./ebcnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/newsebc/live)
        EOL
    - name: Get ebcfinance.m3u8
      run: |
        touch ./ebcfinance.m3u8
        sudo cat >./ebcfinance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=ABn_ccXn_jc&list=PL6GN1rfBAqUvLvwtUNIJ3HlXH3J3OGHwY&index=23)
        EOL
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/寰宇新聞頻道/live)
        EOL
    - name: Get hytv.m3u8
      run: |
        touch ./hytv.m3u8
        sudo cat >./hytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=B7Zp3d6xXWw&list=PL6GN1rfBAqUvLvwtUNIJ3HlXH3J3OGHwY&index=27)
        EOL
    - name: Get tvbs.m3u8
      run: |
        touch ./tvbs.m3u8
        sudo cat >./tvbs.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/TVBSNEWS01/live)
        EOL
    - name: Get tvbsnews.m3u8
      run: |
        touch ./tvbsnews.m3u8
        sudo cat >./tvbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get gstv.m3u8
      run: |
        touch ./gstv.m3u8
        sudo cat >./gstv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCoo-jAsJgM8z09ddlhcBlSA/live)
        EOL
    - name: Get parliamentarytv.m3u8
      run: |
        touch ./parliamentarytv.m3u8
        sudo cat >./parliamentarytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/c/國會頻道/live)
        EOL
    - name: Get ntdaptv.m3u8
      run: |
        touch ./ntdaptv.m3u8
        sudo cat >./ntdaptv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=WIhgU_mc05A)
        EOL
    - name: Get abcnewsau.m3u8
      run: |
        touch ./abcnewsau.m3u8
        sudo cat >./abcnewsau.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/NewsOnABC/live)
        EOL
    - name: Get abcnewsus.m3u8
      run: |
        touch ./abcnewsus.m3u8
        sudo cat >./abcnewsus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/ABCNews/live)
        EOL
    - name: Get abc7news
      run: |
        touch ./abc7news.m3u8
        sudo cat >./abc7news.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/channel/UCq9e_hCv2jvgck8WowW1NXg/live)
        EOL
    - name: Get africanews.m3u8
      run: |
        touch ./africanews.m3u8
        sudo cat >./africanews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/channel/UC1_E8NeF5QHY2dtdLRBCCLA/live)
        EOL
    - name: Get aljazeera.m3u8
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/AlJazeeraEnglish/live)
        EOL
    - name: Get arirangtv.m3u8
      run: |
        touch ./arirangtv.m3u8
        sudo cat >./arirangtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/arirang/live)
        EOL
    - name: Get arirangnews.m3u8
      run: |
        touch ./arirangnews.m3u8
        sudo cat >./arirangnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/watch?v=u7q0KzudBZo)
        EOL
    - name: Get bloombergfinance.m3u8
      run: |
        touch ./bloombergfinance.m3u8
        sudo cat >./bloombergfinance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/Bloomberg/live)
        EOL
    - name: Get bloombergquicktake.m3u8
      run: |
        touch ./bloombergquicktake.m3u8
        sudo cat >./bloombergquicktake.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/channel/UChirEOpgFCupRAk5etXqPaA/live)
        EOL
    - name: Get cna.m3u8
      run: |
        touch ./cna.m3u8
        sudo cat >./cna.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/channelnewsasia/live)
        EOL
    - name: Get cnbc.m3u8
      run: |
        touch ./cnbc.m3u8
        sudo cat >./cnbc.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/cnbc/live)
        EOL
    - name: Get dwnews.m3u8
      run: |
        touch ./dwnews.m3u8
        sudo cat >./dwnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCknLrEdhRCp1aegoMqRaCZg/live)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/EuronewsUSA/live)
        EOL
    - name: Get foxlivenow.m3u8
      run: |
        touch ./foxlivenow.m3u8
        sudo cat >./foxlivenow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCJg9wBPyKMNA5sRDnvzmkdg/live)
        EOL
    - name: Get france24.m3u8
      run: |
        touch ./france24.m3u8
        sudo cat >./france24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/user/france24english/live)
        EOL
    - name: Get gbnews.m3u8
      run: |
        touch ./gbnews.m3u8
        sudo cat >./gbnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UC0vn8ISa4LKMunLbzaXLnOQ/live)
        EOL
    - name: Get nbc2.m3u8
      run: |
        touch ./nbc2.m3u8
        sudo cat >./nbc2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.youtube.com/user/NBC2swfl/live)
        EOL
    - name: Get nbcnewsnow.m3u8
      run: |
        touch ./nbcnewsnow.m3u8
        sudo cat >./nbcnewsnow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCeY0bbntWzzVIaj2z3QigXg/live)
        EOL
    - name: Get newsmax.m3u8
      run: |
        touch ./newsmax.m3u8
        sudo cat >./newsmax.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCx6h-dWzJ5NpAlja1YsApdg/live)
        EOL
    - name: Get nhkworld.m3u8
      run: |
        touch ./nhkworld.m3u8
        sudo cat >./nhkworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(youtube-dl -g https://www.youtube.com/channel/UCSPEjw8F2nQDtmUKPFNF7_A/live)
        EOL
    - name: Get skynews.m3u8
      run: |
        touch ./skynews.m3u8
        sudo cat >./skynews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/user/skynews/live)
        EOL
    - name: Get trtworld.m3u8
      run: |
        touch ./trtworld.m3u8
        sudo cat >./trtworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/channel/UC7fWeaHhqgM4Ry-RMpM2YYw/live)
        EOL
    - name: Get wionnews.m3u8
      run: |
        touch ./wionnews.m3u8
        sudo cat >./wionnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g/live)
        EOL
    - name: Get issviewearth.m3u8
      run: |
        touch ./issviewearth.m3u8
        sudo cat >./issviewearth.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=Y1qQZbTF8iQ)
        EOL
    - name: Get nasaearthview.m3u8
      run: |
        touch ./nasaearthview.m3u8
        sudo cat >./nasaearthview.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=86YLFOog4GM)
        EOL
    - name: Get spaceviewearth.m3u8
      run: |
        touch ./spaceviewearth.m3u8
        sudo cat >./spaceviewearth.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=u-ngXpZKHvI)
        EOL
    - name: Get learnenglish3.m3u8
      run: |
        touch ./learnenglish3.m3u8
        sudo cat >./learnenglish3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=P2zaAPY65xw)
        EOL
    - name: Get learnenglish2.m3u8
      run: |
        touch ./learnenglish2.m3u8
        sudo cat >./learnenglish2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=Gjw8mCMrKFM)
        EOL
    - name: Get learnenglish1.m3u8
      run: |
        touch ./learnenglish1.m3u8
        sudo cat >./learnenglish1.m3u8 <<EOL
        #EXTM3U_sd
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=8VEPLYOOk-w)
        EOL
    - name: Get learnjapanese1.m3u8
      run: |
        touch ./learnjapanese1.m3u8
        sudo cat >./learnjapanese1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=JGGD0-4n_JA)
        EOL
    - name: Get learnjapanese2.m3u8
      run: |
        touch ./learnjapanese2.m3u8
        sudo cat >./learnjapanese2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=KThDy_PhYGU)
        EOL
    - name: Get learnjapanese3.m3u8
      run: |
        touch ./learnjapanese3.m3u8
        sudo cat >./learnjapanese3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.youtube.com/watch?v=fO4T5CoGkm4)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
