name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Get ctsnews.m3u8
      run: |
        touch ./ctsnews.m3u8
        sudo cat >./ctsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@CtsTw/live)
        EOL
    - name: Get cts_news.m3u8
      run: |
        touch ./cts_news.m3u8
        sudo cat >./cts_news.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@CtsTw/live)
        EOL 
    - name: Get ctitv.m3u8
      run: |
        touch ./ctitv.m3u8
        sudo cat >./ctitv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@CtiTv/live)
        EOL
    - name: Get ctitv2.m3u8
   run: |
        touch ./ctitv2.m3u8
        sudo cat >./ctitv2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@CtiDeepThroat/live)
        EOL   
    - name: Get ttvnews.m3u8
      run: |
        touch ./ttvnews.m3u8
        sudo cat >./ttvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@TTV_NEWS/live)
        EOL
    - name: Get ftvnews.m3u8
      run: |
        touch ./ftvnews.m3u8
        sudo cat >./ftvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@FTV_News/live)
        EOL
    - name: Get ctvnews.m3u8
      run: |
        touch ./ctvnews.m3u8
        sudo cat >./ctvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@twctvnews/live)
        EOL
    - name: Get ptsnews.m3u8
      run: |
        touch ./ptsnews.m3u8
        sudo cat >./ptsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@PNNPTS/live)
        EOL
    - name: Get setlive.m3u8
      run: |
        touch ./setlive.m3u8
        sudo cat >./setlive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@setnews/live)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@setinews/live)
        EOL
    - name: Get setnews.m3u8
      run: |
        touch ./setnews.m3u8
        sudo cat >./setnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@setnews/live)
        EOL
    - name: Get ebcnews.m3u8
      run: |
        touch ./ebcnews.m3u8
        sudo cat >./ebcnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/c/newsebc/live)
        EOL
    - name: Get ebcfinance.m3u8
      run: |
        touch ./ebcfinance.m3u8
        sudo cat >./ebcfinance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@57ETFN/live)
        EOL
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@globalnewstw/live)
        EOL
    - name: Get hytv.m3u8
      run: |
        touch ./hytv.m3u8
        sudo cat >./hytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=B7Zp3d6xXWw&list=PL6GN1rfBAqUvLvwtUNIJ3HlXH3J3OGHwY&index=27)
        EOL
    - name: Get tvbshd.m3u8
      run: |
        touch ./tvbshd.m3u8
        sudo cat >./tvbshd.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=YvdcZ_jpLXE)
        EOL
    - name: Get tvbs.m3u8
      run: |
        touch ./tvbs.m3u8
        sudo cat >./tvbs.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get tvbsnews.m3u8
      run: |
        touch ./tvbsnews.m3u8
        sudo cat >./tvbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=m_dhMSvUCIc)
        EOL
    - name: Get tvbslive.m3u8
      run: |
        touch ./tvbslive.m3u8
        sudo cat >./tvbslive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@TVBSNEWS01/live)
        EOL
    - name: Get mnews.m3u8
      run: |
        touch ./mnews.m3u8
        sudo cat >./mnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@mnews-tw/live)
        EOL
    - name: Get gstv.m3u8
      run: |
        touch ./gstv.m3u8
        sudo cat >./gstv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@plus8394/live)
        EOL
    - name: Get parliamentarytv.m3u8
      run: |
        touch ./parliamentarytv.m3u8
        sudo cat >./parliamentarytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/c/國會頻道/live)
        EOL
    - name: Get ntdaptv.m3u8
      run: |
        touch ./ntdaptv.m3u8
        sudo cat >./ntdaptv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/c/NTDAPTV/live)
        EOL
    - name: Get faintv.m3u8
      run: |
        touch ./faintv.m3u8
        sudo cat >./faintv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@user-ru4oy4fp1u/live)
        EOL
    - name: Get 8world.m3u8
      run: |
        touch ./8world.m3u8
        sudo cat >./8world.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@8worldSG/live)
        EOL    
    - name: Get twplus.m3u8
      run: |
        touch ./twplus.m3u8
        sudo cat >./twplus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@TaiwanPlusLive/live)
        EOL
    - name: Get abcnewsau.m3u8
      run: |
        touch ./abcnewsau.m3u8
        sudo cat >./abcnewsau.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/NewsOnABC/live)
        EOL
    - name: Get abcnewsus.m3u8
      run: |
        touch ./abcnewsus.m3u8
        sudo cat >./abcnewsus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/ABCNews/live)
        EOL
    - name: Get abc7news
      run: |
        touch ./abc7news.m3u8
        sudo cat >./abc7news.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@abc7swfl798/live)
        EOL
    - name: Get africanews.m3u8
      run: |
        touch ./africanews.m3u8
        sudo cat >./africanews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@africanews/live)
        EOL
    - name: Get aljazeera.m3u8
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/AlJazeeraEnglish/live)
        EOL
    - name: Get arirangtv.m3u8
      run: |
        touch ./arirangtv.m3u8
        sudo cat >./arirangtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/arirang/live)
        EOL
    - name: Get arirangnews.m3u8
      run: |
        touch ./arirangnews.m3u8
        sudo cat >./arirangnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=u7q0KzudBZo)
        EOL
    - name: Get bloombergfinance.m3u8
      run: |
        touch ./bloombergfinance.m3u8
        sudo cat >./bloombergfinance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/Bloomberg/live)
        EOL
    - name: Get bloombergquicktake.m3u8
      run: |
        touch ./bloombergquicktake.m3u8
        sudo cat >./bloombergquicktake.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@BloombergQuicktake/live)
        EOL
    - name: Get cna.m3u8
      run: |
        touch ./cna.m3u8
        sudo cat >./cna.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/channelnewsasia/live)
        EOL
    - name: Get cnbc.m3u8
      run: |
        touch ./cnbc.m3u8
        sudo cat >./cnbc.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/cnbc/live)
        EOL
    - name: Get dwnews.m3u8
      run: |
        touch ./dwnews.m3u8
        sudo cat >./dwnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@dwnews/live)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/EuronewsUSA/live)
        EOL
    - name: Get foxlivenow.m3u8
      run: |
        touch ./foxlivenow.m3u8
        sudo cat >./foxlivenow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@livenowfox/live)
        EOL
    - name: Get france24.m3u8
      run: |
        touch ./france24.m3u8
        sudo cat >./france24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/user/france24english/live)
        EOL
    - name: Get gbnews.m3u8
      run: |
        touch ./gbnews.m3u8
        sudo cat >./gbnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@GBNewsOnline/live)
        EOL
    - name: Get nbc2.m3u8
      run: |
        touch ./nbc2.m3u8
        sudo cat >./nbc2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/user/NBC2swfl/live)
        EOL
    - name: Get nbcnewsnow.m3u8
      run: |
        touch ./nbcnewsnow.m3u8
        sudo cat >./nbcnewsnow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@NBCNews/live)
        EOL    
    - name: Get newsmax.m3u8
      run: |
        touch ./newsmax.m3u8
        sudo cat >./newsmax.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@NewsmaxTV/live)
        EOL
    - name: Get nhkworld.m3u8
      run: |
        touch ./nhkworld.m3u8
        sudo cat >./nhkworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp --print urls https://www.youtube.com/@NHKWORLDJAPAN/live)
        EOL
    - name: Get skynews.m3u8
      run: |
        touch ./skynews.m3u8
        sudo cat >./skynews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/user/skynews/live)
        EOL
    - name: Get trtworld.m3u8
      run: |
        touch ./trtworld.m3u8
        sudo cat >./trtworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@trtworld/live)
        EOL
    - name: Get wionnews.m3u8
      run: |
        touch ./wionnews.m3u8
        sudo cat >./wionnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/wion/live)
        EOL
    - name: Get issviewearth.m3u8
      run: |
        touch ./issviewearth.m3u8
        sudo cat >./issviewearth.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/@SpaceVideosHD/live)
        EOL
    - name: Get nasaearthview.m3u8
      run: |
        touch ./nasaearthview.m3u8
        sudo cat >./nasaearthview.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=86YLFOog4GM)
        EOL
    - name: Get spaceviewearth.m3u8
      run: |
        touch ./spaceviewearth.m3u8
        sudo cat >./spaceviewearth.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=u-ngXpZKHvI)
        EOL
    - name: Get learnenglish3.m3u8
      run: |
        touch ./learnenglish3.m3u8
        sudo cat >./learnenglish3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=P2zaAPY65xw)
        EOL
    - name: Get learnenglish2.m3u8
      run: |
        touch ./learnenglish2.m3u8
        sudo cat >./learnenglish2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=Gjw8mCMrKFM)
        EOL
    - name: Get learnenglish1.m3u8
      run: |
        touch ./learnenglish1.m3u8
        sudo cat >./learnenglish1.m3u8 <<EOL
        #EXTM3U_sd
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=8VEPLYOOk-w)
        EOL
    - name: Get learnjapanese1.m3u8
      run: |
        touch ./learnjapanese1.m3u8
        sudo cat >./learnjapanese1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=JGGD0-4n_JA)
        EOL
    - name: Get learnjapanese2.m3u8
      run: |
        touch ./learnjapanese2.m3u8
        sudo cat >./learnjapanese2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=KThDy_PhYGU)
        EOL
    - name: Get learnjapanese3.m3u8
      run: |
        touch ./learnjapanese3.m3u8
        sudo cat >./learnjapanese3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=fO4T5CoGkm4)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive